services:
  streamlit:
    build: streamlit
    container_name: tonkatu-st
    image: tonkatu/streamlit
    ports:
      - 8501:8501
    tty: true
    volumes:
      - .:/usr/src/develop
    command: ["bash"]
  jupyter:
    build: jupyter
    container_name: tonkatu-jupyter
    image: tonkatu/jupyter
    ports:
      - 8888:8888
    tty: true
    volumes:
      - .:/usr/src/develop
    command: ["bash"]
  elasticsearch:
    build: elasticsearch
    container_name: tonkatu-es
    image: tonkatu/elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=backlog-cluster
      - bootstrap.memory_lock=true
      - http.max_content_length=2147483647b
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - tonkatu-es:/usr/share/elasticsearch/data

volumes:
  tonkatu-es:
    driver: local
