services:
  streamlit:
    build: streamlit
    container_name: dask-st
    image: datadesk/streamlit
    ports:
      - 8501:8501
    tty: true
    volumes:
      - .:/usr/src/develop
    command: ["bash"]
  notebooks:
    build: notebooks
    container_name: dask-note
    image: datadesk/notebooks
    ports:
      - 8888:8888
    tty: true
    volumes:
      - .:/usr/src/develop
    command: ["bash"]
  elasticsearch:
    build: elasticsearch
    container_name: dask-es
    image: datadesk/elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=backlog-cluster
      - bootstrap.memory_lock=true
      - http.max_content_length=2147483647b
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - dask-es:/usr/share/elasticsearch/data

volumes:
  dask-es:
    driver: local
